create table if not exists public.app_state (
  key text primary key,
  payload jsonb not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.app_state_backups (
  id bigint generated by default as identity primary key,
  state_key text not null,
  payload jsonb not null,
  source_updated_at timestamptz,
  reason text,
  created_at timestamptz not null default now()
);

alter table public.app_state enable row level security;
alter table public.app_state_backups enable row level security;

-- No public policies are intentionally created. The Vercel API uses the
-- Supabase service-role key on the server only, never in the browser.
